### ISSUE TITLE
9. create controller folder 

### ISSUE THREAD

**Issue by salman0ansari** [salman0ansari/hacktoberfest-2022#10]
Create a new folder called `controllers` inside the app folder, 
then create a new file called `note.controller.js`
add following code into file

```node
const Note = require('../models/note.model.js');
```

**Comment by krishna16sharma** [comment]
Hi I'd like to contribute to this.

**Comment by salman0ansari** [comment]
> Hi I'd like to contribute to this.

do #6

**Comment by Misterr-H** [comment]
@salman0ansari 
This one? or #6 ??

**Comment by salman0ansari** [comment]
> @salman0ansari This one? or #6 ??

this

**Comment by Misterr-H** [comment]
@salman0ansari 
Okay, please assign

**Comment by Misterr-H** [comment]
@salman0ansari 
Thanks
