### ISSUE TITLE
2. install necessary modules

### ISSUE THREAD

**Issue by salman0ansari** [salman0ansari/hacktoberfest-2022#2]
by running 
`npm install express mongoose cors --save`

**Comment by kartikjoshi267** [comment]
Please assign this to me

**Comment by kartikjoshi267** [comment]
Please add `hacktoberfest-accepted` to all issues

**Comment by salman0ansari** [comment]
> hacktoberfest-accepted

issues or PRs?

**Comment by kartikjoshi267** [comment]
> > hacktoberfest-accepted
> 
> issues or PRs?

issues so that reach grows

**Comment by salman0ansari** [comment]
> > > hacktoberfest-accepted
> > 
> > 
> > issues or PRs?
> 
> issues so that reach grows

done ty :)
