### ISSUE TITLE
6. defining the note model in mongoose

### ISSUE THREAD

**Issue by salman0ansari** [salman0ansari/hacktoberfest-2022#6]
Create a new folder called `app` inside the `root` folder of the application, 
then create another folder called `models` inside the `app` folder 

Now, create a file called `note.model.js` inside `app/models` folder with the following contents -

```node
const mongoose = require('mongoose');

const NoteSchema = mongoose.Schema({
    title: String,
    content: String
}, {
    timestamps: true
});

module.exports = mongoose.model('Note', NoteSchema);
```

**Comment by SudhanPlayz** [comment]
Assign this to me
